"""
Examination API Routes - Phase 4C
======================================================
Exposes the full examination lifecycle via REST endpoints.

Base prefix:  /api/v1/exams   (registered in router.py)

Endpoints
---------
POST   /generate              → Generate a new exam
GET    /                      → List user's exams
GET    /history               → Exam history (alias for list with semantic name)
GET    /{test_id}             → Full exam detail (metadata + questions)
GET    /{test_id}/questions   → Questions only (student-safe)
POST   /{test_id}/answer      → Save / autosave one answer
GET    /{test_id}/answers     → Retrieve saved answers (page-refresh recovery)
POST   /{test_id}/submit      → Submit the exam

Security
--------
All endpoints require a valid JWT Bearer token.
Only the exam owner can view, answer, or submit their exam.
"""
import logging
from typing import List
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy.orm import Session

from app.api.dependencies import get_current_user
from app.api.v1.endpoints.exam_schemas import (
    APIError,
    APISuccess,
    ExamDetailResponse,
    ExamGenerateRequest,
    ExamSummaryResponse,
    SaveAnswerRequest,
    SavedAnswerResponse,
    SubmitExamData,
    ExamGenerateData,
    SaveAnswerData,
)
from app.db.session import get_db
from app.models.user import User
from app.services.exam_service import ExamService
from app.services.rate_limiter import check_exam_generation_limit

router = APIRouter()
logger = logging.getLogger(__name__)


# ===========================================================================
# ENDPOINT 1 — Generate exam
# ===========================================================================

@router.post(
    "/generate",
    response_model=APISuccess,
    status_code=status.HTTP_201_CREATED,
    summary="Generate Exam",
    description=(
        "Generate a new AI-powered examination. "
        "Questions are retrieved from the RAG vector store and generated by Gemini. "
        "Supports MCQ, Fill-in-the-Blanks, Short Answer, and Long Answer types.\n\n"
        "**Rate:** This endpoint is compute-intensive — avoid calling it in rapid succession."
    ),
    responses={
        201: {
            "description": "Exam generated successfully",
            "content": {
                "application/json": {
                    "example": {
                        "success": True,
                        "message": "Exam generated successfully",
                        "data": {
                            "test_id": "123e4567-e89b-12d3-a456-426614174000",
                            "question_count": 10,
                            "status": "GENERATED",
                        },
                    }
                }
            },
        },
        422: {"description": "Validation error (invalid categories / type / count)"},
        429: {"description": "Rate limit exceeded (max 5 exams per hour)"},
        500: {"description": "Generation failed (Gemini / database error)"},
    },
)
def generate_exam(
    request_body: ExamGenerateRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Generate a new examination.**

    - Validates categories, question type, and count.
    - Retrieves relevant content from ChromaDB (RAG).
    - Calls Gemini AI to generate questions.
    - Persists the exam and questions to PostgreSQL.
    - Returns the exam ID and metadata.

    **Request Body:**
    - `categories`: e.g. `["History", "Politics"]`
    - `question_type`: one of `MCQ | FILL_BLANKS | SHORT_ANSWER | LONG_ANSWER`
    - `question_count`: integer 1–10

    **Security:** Requires Bearer token.
    **Rate Limit:** 5 exams per hour per user.
    """
    # Check rate limit BEFORE processing
    check_exam_generation_limit(current_user.id)
    
    logger.info(
        "POST /exams/generate | user=%s type=%s count=%s",
        current_user.id, request_body.question_type, request_body.question_count,
    )

    data = ExamService.generate_exam(
        db=db,
        user_id=current_user.id,
        categories=request_body.categories,
        question_type=request_body.question_type,
        question_count=request_body.question_count,
    )

    return APISuccess(
        success=True,
        message="Exam generated successfully",
        data=data,
    )


# ===========================================================================
# ENDPOINT 2 — List exams
# ===========================================================================

@router.get(
    "/",
    response_model=APISuccess,
    summary="List My Exams",
    description="Return all exams belonging to the authenticated user, ordered by creation date (newest first).",
    responses={
        200: {
            "description": "Exams retrieved",
            "content": {
                "application/json": {
                    "example": {
                        "success": True,
                        "message": "Exams retrieved successfully",
                        "data": [
                            {
                                "id": "...",
                                "subject": "Social Studies",
                                "question_type": "MCQ",
                                "selected_categories": ["History"],
                                "question_count": 10,
                                "status": "GENERATED",
                                "created_at": "2026-06-11T09:00:00+00:00",
                                "started_at": None,
                                "completed_at": None,
                            }
                        ],
                    }
                }
            },
        }
    },
)
def list_exams(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **List all exams for the current user.**

    Returns compact exam summaries without questions.
    Useful for building a dashboard of exam cards.

    **Security:** Requires Bearer token.
    """
    exams = ExamService.list_exams(db, current_user.id)
    return APISuccess(
        success=True,
        message="Exams retrieved successfully",
        data=exams,
    )


# ===========================================================================
# ENDPOINT 8 — Exam history (MUST be defined BEFORE /{test_id} to avoid
# FastAPI treating 'history' as a UUID path parameter)
# ===========================================================================

@router.get(
    "/history",
    response_model=APISuccess,
    summary="Exam History",
    description=(
        "Return the complete exam history for the authenticated user. "
        "Includes exam type, question count, status, and timestamps."
    ),
    responses={
        200: {"description": "History returned"}
    },
)
def exam_history(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Get exam history.**

    Returns all exams ever generated by this user, newest first.
    Same data as `GET /exams/` — this endpoint exists as a named, semantic alias.

    Fields returned per exam:
    - `id`, `subject`, `question_type`, `selected_categories`
    - `question_count`, `status`
    - `created_at`, `started_at`, `completed_at`

    **Security:** Requires Bearer token.
    """
    history = ExamService.get_history(db, current_user.id)
    return APISuccess(
        success=True,
        message="Exam history retrieved successfully",
        data=history,
    )


# ===========================================================================
# ENDPOINT 9 — Submitted & Evaluated tests (MUST be before /{test_id})
# ===========================================================================

@router.get(
    "/submitted",
    response_model=APISuccess,
    summary="Get Submitted Tests",
    description=(
        "Return all tests with status SUBMITTED or EVALUATED for the authenticated user. "
        "Used by the Evaluation module to show tests that are ready for AI evaluation."
    ),
    responses={
        200: {"description": "Submitted tests returned"},
    },
)
def get_submitted_tests(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Get all submitted and evaluated tests.**

    Returns tests with status SUBMITTED or EVALUATED, ordered newest first.
    These are tests where the student has completed answering and can now
    trigger AI evaluation.

    **Security:** Requires Bearer token.
    """
    from app.repositories.test_repository import TestRepository
    from app.models.enums import TestStatus

    submitted = TestRepository.get_by_user_and_status(
        db, user_id=current_user.id, status=TestStatus.SUBMITTED
    )
    evaluated = TestRepository.get_by_user_and_status(
        db, user_id=current_user.id, status=TestStatus.EVALUATED
    )

    all_tests = submitted + evaluated
    # Sort by created_at descending
    all_tests.sort(key=lambda t: t.created_at, reverse=True)

    tests_data = [
        {
            "id": str(t.id),
            "subject": t.subject,
            "question_type": t.question_type.value if hasattr(t.question_type, "value") else t.question_type,
            "selected_categories": t.selected_categories,
            "question_count": t.question_count,
            "status": t.status.value if hasattr(t.status, "value") else t.status,
            "created_at": t.created_at.isoformat(),
            "started_at": t.started_at.isoformat() if t.started_at else None,
            "completed_at": t.completed_at.isoformat() if t.completed_at else None,
        }
        for t in all_tests
    ]

    return APISuccess(
        success=True,
        message=f"Retrieved {len(tests_data)} submitted tests",
        data={"tests": tests_data, "count": len(tests_data)},
    )


# ===========================================================================
# ENDPOINT 3 — Exam detail
# ===========================================================================

@router.get(
    "/{test_id}",
    response_model=APISuccess,
    summary="Get Exam Detail",
    description=(
        "Return full exam details including metadata and all questions. "
        "Questions are student-safe — `correct_answer` and `model_answer` are never exposed."
    ),
    responses={
        200: {"description": "Exam detail returned"},
        403: {"description": "Not the exam owner"},
        404: {"description": "Exam not found"},
    },
)
def get_exam(
    test_id: UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Get full exam details.**

    Includes:
    - Exam metadata (subject, type, categories, status, timestamps)
    - All questions (NO correct answers or model answers)

    **Path Params:** `test_id` — UUID of the exam.

    **Security:** Only the exam owner can access this endpoint.
    """
    exam = ExamService.get_exam(db, test_id, current_user.id)
    return APISuccess(
        success=True,
        message="Exam retrieved successfully",
        data=exam,
    )


# ===========================================================================
# ENDPOINT 4 — Get questions
# ===========================================================================

@router.get(
    "/{test_id}/questions",
    response_model=APISuccess,
    summary="Get Exam Questions",
    description=(
        "Return all questions for an exam. "
        "Automatically transitions status from GENERATED → IN_PROGRESS on first call. "
        "MCQ questions include `options`; other types only include `question_text`."
    ),
    responses={
        200: {"description": "Questions returned"},
        403: {"description": "Not the exam owner"},
        404: {"description": "Exam not found"},
    },
)
def get_questions(
    test_id: UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Get exam questions (student-safe).**

    Response varies by question type:
    - **MCQ**: `question_text` + `options` (list of 4 strings)
    - **FILL_BLANKS**: `question_text` only (contains `_____`)
    - **SHORT_ANSWER**: `question_text` only
    - **LONG_ANSWER**: `question_text` only

    `correct_answer` and `model_answer` are **never** returned.

    **Security:** Only the exam owner can fetch questions.
    """
    questions = ExamService.get_questions(db, test_id, current_user.id)
    return APISuccess(
        success=True,
        message="Questions retrieved successfully",
        data=questions,
    )


# ===========================================================================
# ENDPOINT 5 — Save answer
# ===========================================================================

@router.post(
    "/{test_id}/answer",
    response_model=APISuccess,
    summary="Save Answer",
    description=(
        "Save or update a student's answer to a question. "
        "Supports autosave — calling this multiple times for the same question updates the answer. "
        "Cannot be called after the exam is submitted."
    ),
    responses={
        200: {
            "description": "Answer saved",
            "content": {
                "application/json": {
                    "example": {
                        "success": True,
                        "message": "Answer saved",
                        "data": {
                            "answer_id": "...",
                            "question_id": "...",
                        },
                    }
                }
            },
        },
        400: {"description": "Exam already submitted or evaluated"},
        403: {"description": "Not the exam owner"},
        404: {"description": "Exam or question not found"},
    },
)
def save_answer(
    test_id: UUID,
    request_body: SaveAnswerRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Save (or update) an answer.**

    - Creates a new answer record if none exists for this question.
    - Updates the existing answer if one already exists.
    - Idempotent — safe to call repeatedly for autosave.

    **Request Body:**
    - `question_id`: UUID of the question
    - `student_answer`: Student's answer text

    **Security:** Only the exam owner can save answers.
    """
    data = ExamService.save_answer(
        db=db,
        test_id=test_id,
        user_id=current_user.id,
        question_id=request_body.question_id,
        student_answer=request_body.student_answer,
    )
    return APISuccess(
        success=True,
        message="Answer saved",
        data=data,
    )


# ===========================================================================
# ENDPOINT 6 — Get answers
# ===========================================================================

@router.get(
    "/{test_id}/answers",
    response_model=APISuccess,
    summary="Get Saved Answers",
    description=(
        "Retrieve all answers saved by the student for this exam. "
        "Use this to restore state after a page refresh."
    ),
    responses={
        200: {"description": "Saved answers returned"},
        403: {"description": "Not the exam owner"},
        404: {"description": "Exam not found"},
    },
)
def get_answers(
    test_id: UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Retrieve all saved answers.**

    Returns:
    - `answer_id`
    - `question_id`
    - `student_answer` (may be null if saved without a value)
    - `updated_at`

    Useful for restoring answer state when the student refreshes the page.

    **Security:** Only the exam owner can retrieve answers.
    """
    answers = ExamService.get_answers(db, test_id, current_user.id)
    return APISuccess(
        success=True,
        message="Answers retrieved successfully",
        data=answers,
    )


# ===========================================================================
# ENDPOINT 7 — Submit exam
# ===========================================================================

@router.post(
    "/{test_id}/submit",
    response_model=APISuccess,
    summary="Submit Exam",
    description=(
        "Submit the exam. Sets status to SUBMITTED and records the completion timestamp. "
        "Cannot be undone. Cannot be called twice."
    ),
    responses={
        200: {
            "description": "Exam submitted successfully",
            "content": {
                "application/json": {
                    "example": {
                        "success": True,
                        "message": "Exam submitted successfully",
                        "data": {
                            "test_id": "...",
                            "status": "SUBMITTED",
                            "completed_at": "2026-06-11T10:00:00+00:00",
                            "questions_answered": 9,
                            "total_questions": 10,
                        },
                    }
                }
            },
        },
        400: {"description": "Exam already submitted or evaluated"},
        403: {"description": "Not the exam owner"},
        404: {"description": "Exam not found"},
    },
)
def submit_exam(
    test_id: UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Submit the exam.**

    - Marks status as `SUBMITTED`.
    - Records `completed_at` timestamp.
    - Returns submission summary (answered count vs total).

    **Security:** Only the exam owner can submit.
    """
    data = ExamService.submit_exam(db, test_id, current_user.id)
    return APISuccess(
        success=True,
        message="Exam submitted successfully",
        data=data,
    )


# ===========================================================================
# ENDPOINT 9 — Delete exam
# ===========================================================================

@router.delete(
    "/{test_id}",
    response_model=APISuccess,
    summary="Delete Exam",
    description=(
        "Delete an exam and all associated data (questions and student answers). "
        "This action is permanent and cannot be undone."
    ),
    responses={
        200: {
            "description": "Exam deleted successfully",
            "content": {
                "application/json": {
                    "example": {
                        "success": True,
                        "message": "Exam deleted successfully",
                        "data": {
                            "test_id": "123e4567-e89b-12d3-a456-426614174000",
                            "message": "Exam deleted successfully"
                        },
                    }
                }
            },
        },
        403: {"description": "Not the exam owner"},
        404: {"description": "Exam not found"},
    },
)
def delete_exam(
    test_id: UUID,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """
    **Delete an exam permanently.**

    - Deletes the exam and all associated questions and student answers.
    - Cannot be undone.
    - Only the exam owner can delete.

    **Security:** Requires Bearer token and ownership verification.
    """
    data = ExamService.delete_exam(db, test_id, current_user.id)
    return APISuccess(
        success=True,
        message="Exam deleted successfully",
        data=data,
    )




